// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "types": prism TestHelpers
//
// Command:
// $ goagen
// --design=github.com/nikhil-thomas/technik-dojo/goa-exp/goa-examples/02_types/design
// --out=$(GOPATH)/src/github.com/nikhil-thomas/technik-dojo/goa-exp/goa-examples/02_types
// --version=v1.3.1

package test

import (
	"bytes"
	"context"
	"fmt"
	"github.com/goadesign/goa"
	"github.com/goadesign/goa/goatest"
	"github.com/nikhil-thomas/technik-dojo/goa-exp/goa-examples/02_types/app"
	uuid "github.com/satori/go.uuid"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"time"
)

// ShowPrismOK runs the method Show of the given controller with the given parameters.
// It returns the response writer so it's possible to inspect the response headers and the media type struct written to the response.
// If ctx is nil then context.Background() is used.
// If service is nil then a default service is created.
func ShowPrismOK(t goatest.TInterface, ctx context.Context, service *goa.Service, ctrl app.PrismController, anyParam interface{}, boolParam *bool, dateTimeParam *time.Time, intParam *int, numParam *float64, stringParam *string, uuidParam *uuid.UUID) (http.ResponseWriter, *app.GoadesignExamplesPrism) {
	// Setup service
	var (
		logBuf bytes.Buffer
		resp   interface{}

		respSetter goatest.ResponseSetterFunc = func(r interface{}) { resp = r }
	)
	if service == nil {
		service = goatest.Service(&logBuf, respSetter)
	} else {
		logger := log.New(&logBuf, "", log.Ltime)
		service.WithLogger(goa.NewLogger(logger))
		newEncoder := func(io.Writer) goa.Encoder { return respSetter }
		service.Encoder = goa.NewHTTPEncoder() // Make sure the code ends up using this decoder
		service.Encoder.Register(newEncoder, "*/*")
	}

	// Setup request context
	rw := httptest.NewRecorder()
	query := url.Values{}
	{
		sliceVal := []string{fmt.Sprintf("%v", anyParam)}
		query["any_param"] = sliceVal
	}
	if boolParam != nil {
		sliceVal := []string{fmt.Sprintf("%v", *boolParam)}
		query["bool_param"] = sliceVal
	}
	if dateTimeParam != nil {
		sliceVal := []string{(*dateTimeParam).Format(time.RFC3339)}
		query["date_time_param"] = sliceVal
	}
	if intParam != nil {
		sliceVal := []string{strconv.Itoa(*intParam)}
		query["int_param"] = sliceVal
	}
	if numParam != nil {
		sliceVal := []string{fmt.Sprintf("%v", *numParam)}
		query["num_param"] = sliceVal
	}
	if stringParam != nil {
		sliceVal := []string{*stringParam}
		query["string_param"] = sliceVal
	}
	if uuidParam != nil {
		sliceVal := []string{fmt.Sprintf("%v", *uuidParam)}
		query["uuid_param"] = sliceVal
	}
	u := &url.URL{
		Path:     fmt.Sprintf("/"),
		RawQuery: query.Encode(),
	}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		panic("invalid test " + err.Error()) // bug
	}
	prms := url.Values{}
	{
		sliceVal := []string{fmt.Sprintf("%v", anyParam)}
		prms["any_param"] = sliceVal
	}
	if boolParam != nil {
		sliceVal := []string{fmt.Sprintf("%v", *boolParam)}
		prms["bool_param"] = sliceVal
	}
	if dateTimeParam != nil {
		sliceVal := []string{(*dateTimeParam).Format(time.RFC3339)}
		prms["date_time_param"] = sliceVal
	}
	if intParam != nil {
		sliceVal := []string{strconv.Itoa(*intParam)}
		prms["int_param"] = sliceVal
	}
	if numParam != nil {
		sliceVal := []string{fmt.Sprintf("%v", *numParam)}
		prms["num_param"] = sliceVal
	}
	if stringParam != nil {
		sliceVal := []string{*stringParam}
		prms["string_param"] = sliceVal
	}
	if uuidParam != nil {
		sliceVal := []string{fmt.Sprintf("%v", *uuidParam)}
		prms["uuid_param"] = sliceVal
	}
	if ctx == nil {
		ctx = context.Background()
	}
	goaCtx := goa.NewContext(goa.WithAction(ctx, "PrismTest"), rw, req, prms)
	showCtx, _err := app.NewShowPrismContext(goaCtx, req, service)
	if _err != nil {
		e, ok := _err.(goa.ServiceError)
		if !ok {
			panic("invalid test data " + _err.Error()) // bug
		}
		t.Errorf("unexpected parameter validation error: %+v", e)
		return nil, nil
	}

	// Perform action
	_err = ctrl.Show(showCtx)

	// Validate response
	if _err != nil {
		t.Fatalf("controller returned %+v, logs:\n%s", _err, logBuf.String())
	}
	if rw.Code != 200 {
		t.Errorf("invalid response status code: got %+v, expected 200", rw.Code)
	}
	var mt *app.GoadesignExamplesPrism
	if resp != nil {
		var _ok bool
		mt, _ok = resp.(*app.GoadesignExamplesPrism)
		if !_ok {
			t.Fatalf("invalid response media: got variable of type %T, value %+v, expected instance of app.GoadesignExamplesPrism", resp, resp)
		}
	}

	// Return results
	return rw, mt
}
