// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "types": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/nikhil-thomas/technik-dojo/goa-exp/goa-examples/02_types/design
// --out=$(GOPATH)/src/github.com/nikhil-thomas/technik-dojo/goa-exp/goa-examples/02_types
// --version=v1.3.1

package app

// ArrayPrismHref returns the resource href.
func ArrayPrismHref() string {
	return "/array"
}

// HashPrismHref returns the resource href.
func HashPrismHref() string {
	return "/hash"
}

// PrismHref returns the resource href.
func PrismHref() string {
	return "/"
}
