// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "URL shortner API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/nikhil-thomas/technik-dojo/goa-exp/goa-url-shortner/design
// --out=$(GOPATH)/src/github.com/nikhil-thomas/technik-dojo/goa-exp/goa-url-shortner
// --version=v1.3.1

package app
