// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application User Types
//
// Command:
// $ goagen
// --design=github.com/nikhil-thomas/technik-dojo/goa-exp/goa-examples/01_adder/design
// --out=$(GOPATH)/src/github.com/nikhil-thomas/technik-dojo/goa-exp/goa-examples/01_adder
// --version=v1.3.1

package app
